# Generated by Django 4.1 on 2022-08-30 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='esm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coe', models.IntegerField()),
                ('intercept', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Regres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
                ('name', models.ManyToManyField(related_name='esme', to='regression.esm')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='regression.parameters')),
            ],
        ),
    ]
