# Generated by Django 4.0.6 on 2022-08-30 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Regres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveIntegerField()),
                ('y', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coe', models.IntegerField()),
                ('intercept', models.IntegerField()),
                ('regre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regression', to='regression.regres')),
            ],
        ),
    ]
